import { emitASUnmanagedFromSchema } from './schema';
import {
  readAscRecordSchema,
  type AscRecordField,
  type AscRecordFieldType,
  type AscRecordSchema,
} from './records';

export { loadASC } from './load';
export { asPrelude } from './prelude';
export { genericASModuleSource } from './generic';
export { buildOpsForParent } from './ops';
export { emitASUnmanagedFromSchema } from './schema';
export { ascField, ascRecord, readAscRecordSchema } from './records';
export type { AscRecordField, AscRecordFieldType, AscRecordSchema } from './records';

export type AscGeneratedRecordFieldType = AscRecordFieldType;

export type AscGeneratedSchemaRef = {
  module: string;
  export?: string;
  initialize?: false | Record<string, unknown>;
};

export type AscGeneratedRecordField = AscRecordField;

export type AscGeneratedRecord = AscRecordSchema;
export type AscGeneratedRecordRef = AscGeneratedSchemaRef;

export type AscGeneratedFileConfig = {
  outFile: string;
  schemas?: AscGeneratedSchemaRef[];
  records?: Array<AscGeneratedRecord | AscGeneratedRecordRef>;
};

export type AscPrecompileConfig = {
  inputPaths: string[];
  outFile: string;
  generatedFiles?: AscGeneratedFileConfig[];
  gzipFile?: string;
  base64File?: string;
  base64ExportName?: string;
  base64Source?: 'outFile' | 'gzipFile';
  textFile?: string;
  sourceMap?: boolean;
  debug?: boolean;
  optimizeLevel?: 0 | 1 | 2 | 3 | 4;
  shrinkLevel?: 0 | 1 | 2;
  runtime?: 'stub' | 'minimal' | 'incremental';
  simd?: boolean;
  noAssert?: boolean;
};

export async function precompileAssemblyScript(config: AscPrecompileConfig): Promise<{
  outFile: string;
  gzipFile?: string;
  base64File?: string;
  textFile?: string;
}> {
  if (!config.inputPaths?.length) {
    throw new Error('precompileAssemblyScript requires at least one input path');
  }
  if (!config.outFile) {
    throw new Error('precompileAssemblyScript requires outFile');
  }

  if (config.generatedFiles?.length) {
    await Promise.all(config.generatedFiles.map(file => writeGeneratedAscFile(file)));
  }

  const { loadASC } = await import('./load.js');
  const asc = await loadASC();

  const args = [
    ...config.inputPaths,
    '--outFile',
    config.outFile,
    ...(config.textFile ? ['--textFile', config.textFile] : []),
    ...(config.sourceMap ? ['--sourceMap'] : []),
    ...(config.debug ? ['--debug'] : ['--optimizeLevel', String(config.optimizeLevel ?? 3)]),
    ...(config.shrinkLevel != null ? ['--shrinkLevel', String(config.shrinkLevel)] : []),
    ...((config.noAssert ?? true) ? ['--noAssert'] : []),
    ...((config.simd ?? true) ? ['--enable', 'simd'] : []),
    '--runtime',
    config.runtime ?? 'stub',
    '--noColors',
  ];

  const result = await asc.main(args);
  if (result?.error) {
    throw new Error(`AssemblyScript precompile failed: ${result.error.message ?? result.error}`);
  }

  if (config.gzipFile) {
    const [{ readFile, writeFile, mkdir }, { dirname }, { gzip }] = await Promise.all([
      import('node:fs/promises'),
      import('node:path'),
      import('node:zlib'),
    ]);
    const { promisify } = await import('node:util');
    const compressed = await promisify(gzip)(await readFile(config.outFile), { level: 9 });
    await mkdir(dirname(config.gzipFile), { recursive: true });
    await writeFile(config.gzipFile, compressed);
  }

  if (config.base64File) {
    const [{ readFile, writeFile, mkdir }, { dirname }] = await Promise.all([
      import('node:fs/promises'),
      import('node:path'),
    ]);
    const sourceFile =
      config.base64Source === 'gzipFile'
        ? config.gzipFile
        : config.base64Source === 'outFile'
          ? config.outFile
          : (config.gzipFile ?? config.outFile);
    if (!sourceFile) {
      throw new Error('base64Source "gzipFile" requires gzipFile');
    }
    const exportName = config.base64ExportName ?? 'SHADO_WASM_BASE64';
    const base64 = (await readFile(sourceFile)).toString('base64');
    await mkdir(dirname(config.base64File), { recursive: true });
    await writeFile(
      config.base64File,
      ['// Generated by shado asc build.', `export const ${exportName} = "${base64}";`, ''].join(
        '\n'
      )
    );
  }

  return {
    outFile: config.outFile,
    gzipFile: config.gzipFile,
    base64File: config.base64File,
    textFile: config.textFile,
  };
}

async function writeGeneratedAscFile(config: AscGeneratedFileConfig): Promise<void> {
  const [{ writeFile, mkdir }, { dirname }] = await Promise.all([
    import('node:fs/promises'),
    import('node:path'),
  ]);
  const parts = ['// Generated by shado asc build. Do not edit.', ''];
  for (const schemaRef of config.schemas ?? []) {
    const schema = await resolveSchemaRef(schemaRef);
    parts.push(emitASUnmanagedFromSchema(schema), '');
  }
  for (const record of config.records ?? []) {
    parts.push(emitASRecord(await resolveRecord(record)), '');
  }
  await mkdir(dirname(config.outFile), { recursive: true });
  await writeFile(config.outFile, parts.join('\n'));
}

async function resolveRecord(
  record: AscGeneratedRecord | AscGeneratedRecordRef
): Promise<AscGeneratedRecord> {
  if ('fields' in record) return record;
  const ctor = await resolveExportRef(record);
  const schema = readAscRecordSchema(ctor);
  if (!schema) {
    throw new Error(`${ctor.name ?? record.module} does not expose a Shado ASC record schema`);
  }
  return schema;
}

async function resolveSchemaRef(ref: AscGeneratedSchemaRef): Promise<any> {
  const ctor = await resolveExportRef(ref);
  const initialize = ref.initialize;
  if (initialize !== false && typeof ctor.initialize === 'function') {
    const ok = await ctor.initialize({}, { wasm: false, ...(initialize ?? {}) });
    if (!ok) throw new Error(`${ctor.name ?? ref.module}.initialize() failed`);
  }
  const schema =
    ctor.schema ?? (typeof ctor.getSchema === 'function' ? ctor.getSchema([]) : undefined);
  if (!schema) {
    throw new Error(`${ctor.name ?? ref.module} does not expose a Shado schema`);
  }
  return schema;
}

async function resolveExportRef(ref: AscGeneratedSchemaRef): Promise<any> {
  const { pathToFileURL } = await import('node:url');
  const { resolve } = await import('node:path');
  const specifier =
    ref.module.startsWith('.') || ref.module.startsWith('/')
      ? pathToFileURL(resolve(process.cwd(), ref.module)).href
      : ref.module;
  const mod = await import(specifier);
  const ctor = ref.export ? mod[ref.export] : (mod.default ?? mod);
  if (!ctor) {
    throw new Error(`Could not resolve ${ref.export ?? 'default'} from ${ref.module}`);
  }
  return ctor;
}

function emitASRecord(record: AscGeneratedRecord): string {
  const lines: string[] = [];
  const offsets: Array<{ name: string; offset: number }> = [];
  let cursor = 0;
  let padIndex = 0;
  lines.push(`@unmanaged`);
  lines.push(`export class ${record.name} {`);
  for (const field of record.fields) {
    const offset = field.byteOffset ?? cursor;
    if (offset < cursor) {
      throw new Error(`${record.name}.${field.name} overlaps previous field`);
    }
    while (cursor < offset) {
      lines.push(`  __pad${padIndex++}: u8;`);
      cursor++;
    }
    offsets.push({ name: field.name, offset });
    const emitted = emitASRecordField(field.name, field.type);
    for (const line of emitted.lines) lines.push(`  ${line}`);
    cursor += emitted.byteSize;
  }
  const byteSize = record.byteSize ?? cursor;
  if (byteSize < cursor) {
    throw new Error(`${record.name}.byteSize ${byteSize} is smaller than emitted ${cursor}`);
  }
  while (cursor < byteSize) {
    lines.push(`  __pad${padIndex++}: u8;`);
    cursor++;
  }
  lines.push(`}`);
  for (const field of offsets) {
    lines.push(`export const OFFSET_${record.name}_${field.name}: i32 = ${field.offset};`);
  }
  lines.push(`export const SIZEOF_${record.name}: i32 = ${byteSize};`);
  return lines.join('\n');
}

function emitASRecordField(
  name: string,
  type: AscGeneratedRecordFieldType
): { lines: string[]; byteSize: number } {
  switch (type) {
    case 'i32':
    case 'u32':
    case 'f32':
    case 'f64':
      return { lines: [`${name}: ${type};`], byteSize: type === 'f64' ? 8 : 4 };
    case 'vec2':
      return { lines: [`${name}_x: f32; ${name}_y: f32;`], byteSize: 8 };
    case 'vec3':
      return { lines: [`${name}_x: f32; ${name}_y: f32; ${name}_z: f32;`], byteSize: 12 };
    case 'vec4':
      return {
        lines: [`${name}_x: f32; ${name}_y: f32; ${name}_z: f32; ${name}_w: f32;`],
        byteSize: 16,
      };
  }
}
