import type { AoSScalarType } from '../schema/AoSLayout';
import {
  compileNetLayouts,
  type NetFieldLayout,
  type NetStructLayout,
  type NetStructSpec,
} from './NetLayout';

export interface EmitNetStructRustModuleOptions {
  banner?: string;
  /**
   * Where `Vec` comes from. `alloc` suits `#![no_std]` crates that declare
   * `extern crate alloc` at their root; `std` is the default.
   */
  vec?: 'std' | 'alloc';
}

/**
 * Emit a dependency-free Rust module whose packets are byte-identical to the
 * ones `emitNetStructModule` produces from the same specs: the same 32-byte
 * header, schema hashes, record strides and SoA plane placement.
 *
 * Records are owned value types rather than in-place views, and every read and
 * write is an explicit little-endian copy at a compiled offset, so the module
 * needs no `unsafe` and does not depend on Rust's own struct layout.
 */
export function emitNetStructRustModule(
  specs: readonly NetStructSpec[],
  options: EmitNetStructRustModuleOptions = {}
): string {
  const layouts = compileNetLayouts(specs);
  const vec = options.vec === 'alloc' ? 'alloc::vec::Vec' : 'std::vec::Vec';
  const lines = [
    options.banner ?? '// Generated by Shado. Do not edit by hand.',
    '',
    '#![allow(dead_code, clippy::all)]',
    '',
    `use ${vec};`,
    '',
    '// The 32-byte header keeps every payload naturally aligned for Wasm/GPU copies.',
    'pub const NET_HEADER_BYTES: usize = 32;',
    'pub const NET_MAGIC: u32 = 0x544e5348; // "SHNT" in little-endian bytes',
    'pub const NET_CODEC_VERSION: u16 = 1;',
    '',
    emitRuntime(),
    '',
  ];

  const declarations: string[] = [];
  const emitted = new Set<string>();
  for (const spec of specs) {
    const layout = layouts.get(spec.name)!;
    emitRecord(layout, layout.name, declarations, emitted);
  }
  lines.push(declarations.join('\n\n'), '');
  for (const spec of specs) lines.push(emitPacket(layouts.get(spec.name)!), '');
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitPacket(layout: NetStructLayout): string {
  const constant = constantName(layout.name);
  const header = `pub const ${constant}_SCHEMA_ID: u32 = 0x${layout.schemaId.toString(16)};
pub const ${constant}_VERSION: u16 = ${layout.version};
pub const ${constant}_STRIDE: usize = ${layout.stride};
pub const ${constant}_SCHEMA_HASH: u64 = 0x${layout.schemaHash.toString(16)};`;
  if (layout.storage === 'soa') return `${header}\n\n${emitSoABatch(layout, constant)}`;
  return `${header}

impl NetPacket for ${layout.name} {
    const SCHEMA_ID: u32 = ${constant}_SCHEMA_ID;
    const VERSION: u16 = ${constant}_VERSION;
    const SCHEMA_HASH: u64 = ${constant}_SCHEMA_HASH;
}`;
}

function emitRecord(
  layout: NetStructLayout,
  typeName: string,
  output: string[],
  emitted: Set<string>
): void {
  if (emitted.has(typeName)) return;
  emitted.add(typeName);

  for (const field of layout.fields) {
    if (field.kind !== 'struct') continue;
    emitRecord(field.struct, nestedName(field, typeName), output, emitted);
  }

  const members = layout.fields.map(
    field => `    pub ${rustIdent(field.name)}: ${fieldRustType(field, typeName)},`
  );
  const defaults = layout.fields.map(
    field => `            ${rustIdent(field.name)}: ${fieldDefault(field, typeName)},`
  );
  const writes = layout.fields.map(emitFieldWrite);
  const reads = layout.fields.map(field => emitFieldRead(field, typeName));
  const kinds = layout.variants.length ? emitKinds(layout, typeName) : '';

  output.push(`#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ${typeName} {
${members.join('\n')}
}

impl Default for ${typeName} {
    fn default() -> Self {
        Self {
${defaults.join('\n')}
        }
    }
}

impl NetRecord for ${typeName} {
    const STRIDE: usize = ${layout.stride};

    fn write_record(&self, out: &mut [u8]) {
${writes.map(line => indent(line, 8)).join('\n')}
    }

    fn read_record(bytes: &[u8]) -> Self {
        Self {
${reads.map(line => indent(line, 12)).join('\n')}
        }
    }
}${kinds}`);
}

function emitKinds(layout: NetStructLayout, typeName: string): string {
  const kind = layout.fields.find(field => field.name === 'kind')!;
  const type = kind.kind === 'scalar' ? rustScalar(kind.type) : 'u32';
  const constants = layout.variants.map(
    variant => `    pub const KIND_${constantName(variant.name)}: ${type} = ${variant.tag};`
  );
  return `

impl ${typeName} {
${constants.join('\n')}
}`;
}

function emitFieldWrite(field: NetFieldLayout): string {
  const name = rustIdent(field.name);
  if (field.kind === 'struct') {
    const stride = field.struct.stride;
    if (field.count === 1) {
      return `self.${name}.write_record(&mut out[${field.byteOffset}..${field.byteOffset + stride}]);`;
    }
    return `for (i, item) in self.${name}.iter().enumerate() {
    let at = ${field.byteOffset} + i * ${stride};
    item.write_record(&mut out[at..at + ${stride}]);
}`;
  }
  const size = scalarByteSize(field.type);
  const put = `put_${field.type}`;
  if (field.count === 1) return `${put}(out, ${field.byteOffset}, self.${name});`;
  return `for (i, value) in self.${name}.iter().enumerate() {
    ${put}(out, ${field.byteOffset} + i * ${size}, *value);
}`;
}

function emitFieldRead(field: NetFieldLayout, owner: string): string {
  const name = rustIdent(field.name);
  if (field.kind === 'struct') {
    const nested = nestedName(field, owner);
    const stride = field.struct.stride;
    if (field.count === 1) {
      return `${name}: ${nested}::read_record(&bytes[${field.byteOffset}..${field.byteOffset + stride}]),`;
    }
    return `${name}: core::array::from_fn(|i| {
    let at = ${field.byteOffset} + i * ${stride};
    ${nested}::read_record(&bytes[at..at + ${stride}])
}),`;
  }
  const get = `get_${field.type}`;
  if (field.count === 1) return `${name}: ${get}(bytes, ${field.byteOffset}),`;
  return `${name}: core::array::from_fn(|i| ${get}(bytes, ${field.byteOffset} + i * ${scalarByteSize(field.type)})),`;
}

interface RustSoAPlane {
  /** Batch member name, e.g. `state_position`. */
  member: string;
  /** Path to the value inside one row, e.g. `state.position`. */
  rowPath: string;
  type: AoSScalarType;
  components: number;
  alignment: number;
  scalarBytes: number;
}

function flattenSoAPlanes(layout: NetStructLayout, prefix = '', rowPrefix = ''): RustSoAPlane[] {
  return layout.fields.flatMap(field => {
    const member = prefix ? `${prefix}_${snakeCase(field.name)}` : snakeCase(field.name);
    const rowPath = rowPrefix ? `${rowPrefix}.${rustIdent(field.name)}` : rustIdent(field.name);
    if (field.kind === 'struct') {
      if (field.count !== 1) {
        throw new Error(
          `${layout.name}.${field.name}: SoA nested arrays require an explicit schema`
        );
      }
      return flattenSoAPlanes(field.struct, member, rowPath);
    }
    return [
      {
        member,
        rowPath,
        type: field.type,
        components: field.count,
        alignment: field.alignment,
        scalarBytes: field.byteSize / field.count,
      },
    ];
  });
}

function emitSoABatch(layout: NetStructLayout, constant: string): string {
  const batch = `${layout.name}Batch`;
  const planes = flattenSoAPlanes(layout);
  const members = planes.map(
    plane =>
      `    /// ${plane.components === 1 ? 'One value per row.' : `${plane.components} values per row, row-major.`}\n    pub ${rustIdent(plane.member)}: Vec<${rustScalar(plane.type)}>,`
  );
  const zeroed = planes.map(
    plane =>
      `            ${rustIdent(plane.member)}: vec_of(count * ${plane.components}, ${scalarDefault(plane.type)}),`
  );
  const encode = planes.map(plane => {
    const member = rustIdent(plane.member);
    return `at = align_up(at, ${plane.alignment});
check_plane(self.${member}.len(), self.count * ${plane.components}, "${layout.name}.${plane.member}");
for (i, value) in self.${member}.iter().enumerate() {
    put_${plane.type}(payload, at + i * ${plane.scalarBytes}, *value);
}
at += ${plane.scalarBytes * plane.components} * self.count;`;
  });
  const decode = planes.map(plane => {
    const member = rustIdent(plane.member);
    return `at = align_up(at, ${plane.alignment});
let mut ${member} = Vec::with_capacity(count * ${plane.components});
for i in 0..count * ${plane.components} {
    ${member}.push(get_${plane.type}(payload, at + i * ${plane.scalarBytes}));
}
at += ${plane.scalarBytes * plane.components} * count;`;
  });
  const memberList = planes.map(plane => `            ${rustIdent(plane.member)},`);
  const rowReads = planes.map(plane => {
    const member = rustIdent(plane.member);
    if (plane.components === 1) return `row.${plane.rowPath} = self.${member}[index];`;
    return `row.${plane.rowPath}.copy_from_slice(&self.${member}[index * ${plane.components}..(index + 1) * ${plane.components}]);`;
  });
  const rowWrites = planes.map(plane => {
    const member = rustIdent(plane.member);
    if (plane.components === 1) return `self.${member}[index] = row.${plane.rowPath};`;
    return `self.${member}[index * ${plane.components}..(index + 1) * ${plane.components}].copy_from_slice(&row.${plane.rowPath});`;
  });

  return `/// Column-major batch of \`${layout.name}\` rows: one plane per scalar field,
/// laid out back to back in the payload exactly as the TypeScript view reads it.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ${batch} {
    pub count: usize,
${members.join('\n')}
}

impl ${batch} {
    pub const SCHEMA_ID: u32 = ${constant}_SCHEMA_ID;
    pub const VERSION: u16 = ${constant}_VERSION;
    pub const STRIDE: usize = ${constant}_STRIDE;
    pub const SCHEMA_HASH: u64 = ${constant}_SCHEMA_HASH;

    /// A batch of \`count\` zeroed rows.
    pub fn with_count(count: usize) -> Self {
        Self {
            count,
${zeroed.join('\n')}
        }
    }

    pub fn from_rows(rows: &[${layout.name}]) -> Self {
        let mut batch = Self::with_count(rows.len());
        for (index, row) in rows.iter().enumerate() {
            batch.set_row(index, row);
        }
        batch
    }

    pub fn row(&self, index: usize) -> ${layout.name} {
        let mut row = ${layout.name}::default();
${rowReads.map(line => indent(line, 8)).join('\n')}
        row
    }

    pub fn set_row(&mut self, index: usize, row: &${layout.name}) {
${rowWrites.map(line => indent(line, 8)).join('\n')}
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut bytes = net_packet(
            Self::SCHEMA_ID,
            Self::VERSION,
            Self::SCHEMA_HASH,
            Self::STRIDE,
            self.count,
        );
        let payload = &mut bytes[NET_HEADER_BYTES..];
        let mut at = 0usize;
${encode.map(line => indent(line, 8)).join('\n')}
        let _ = at;
        bytes
    }

    pub fn decode(bytes: &[u8]) -> Result<Self, NetDecodeError> {
        let count = read_net_header(
            bytes,
            Self::SCHEMA_ID,
            Self::VERSION,
            Self::SCHEMA_HASH,
            Self::STRIDE,
        )?;
        let payload = &bytes[NET_HEADER_BYTES..];
        let mut at = 0usize;
${decode.map(line => indent(line, 8)).join('\n')}
        let _ = at;
        Ok(Self {
            count,
${memberList.join('\n')}
        })
    }
}`;
}

function emitRuntime(): string {
  const scalars: AoSScalarType[] = [
    'i8',
    'u8',
    'i16',
    'u16',
    'i32',
    'u32',
    'f32',
    'i64',
    'u64',
    'f64',
  ];
  const accessors = scalars
    .map(type => {
      const size = scalarByteSize(type);
      return `#[inline]
fn get_${type}(bytes: &[u8], at: usize) -> ${type} {
    let mut raw = [0u8; ${size}];
    raw.copy_from_slice(&bytes[at..at + ${size}]);
    ${type}::from_le_bytes(raw)
}

#[inline]
fn put_${type}(bytes: &mut [u8], at: usize, value: ${type}) {
    bytes[at..at + ${size}].copy_from_slice(&value.to_le_bytes());
}`;
    })
    .join('\n\n');

  return `#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NetDecodeError {
    /** Fewer bytes than a header. */
    Truncated,
    /** Magic, codec version, schema id, schema version, header size, hash or stride differ. */
    SchemaMismatch,
    /** The payload is not exactly \`stride * count\` bytes. */
    InvalidLength,
    /** A single-record decode found an empty batch. */
    Empty,
}

/// One fixed-width record, written at the offsets the schema compiled to.
pub trait NetRecord: Sized {
    const STRIDE: usize;
    /// Write into \`out\`, which is exactly \`STRIDE\` bytes and already zeroed.
    fn write_record(&self, out: &mut [u8]);
    /// Read from \`bytes\`, which is exactly \`STRIDE\` bytes.
    fn read_record(bytes: &[u8]) -> Self;
}

/// A record with its own packet identity, sent as an array-of-structs batch.
pub trait NetPacket: NetRecord {
    const SCHEMA_ID: u32;
    const VERSION: u16;
    const SCHEMA_HASH: u64;

    fn encode(&self) -> Vec<u8> {
        encode_net_batch(core::slice::from_ref(self))
    }

    /// The first record of a packet, like the TypeScript \`decode*\` helpers.
    fn decode(bytes: &[u8]) -> Result<Self, NetDecodeError> {
        let count = read_net_header(bytes, Self::SCHEMA_ID, Self::VERSION, Self::SCHEMA_HASH, Self::STRIDE)?;
        if count == 0 {
            return Err(NetDecodeError::Empty);
        }
        Ok(Self::read_record(&bytes[NET_HEADER_BYTES..NET_HEADER_BYTES + Self::STRIDE]))
    }
}

pub fn encode_net_batch<T: NetPacket>(records: &[T]) -> Vec<u8> {
    let mut bytes = net_packet(T::SCHEMA_ID, T::VERSION, T::SCHEMA_HASH, T::STRIDE, records.len());
    for (i, record) in records.iter().enumerate() {
        let at = NET_HEADER_BYTES + i * T::STRIDE;
        record.write_record(&mut bytes[at..at + T::STRIDE]);
    }
    bytes
}

pub fn decode_net_batch<T: NetPacket>(bytes: &[u8]) -> Result<Vec<T>, NetDecodeError> {
    let count = read_net_header(bytes, T::SCHEMA_ID, T::VERSION, T::SCHEMA_HASH, T::STRIDE)?;
    let mut records = Vec::with_capacity(count);
    for i in 0..count {
        let at = NET_HEADER_BYTES + i * T::STRIDE;
        records.push(T::read_record(&bytes[at..at + T::STRIDE]));
    }
    Ok(records)
}

/// The schema id of a packet without validating the rest of it, for routing.
pub fn peek_net_schema_id(bytes: &[u8]) -> Option<u32> {
    if bytes.len() < NET_HEADER_BYTES || get_u32(bytes, 0) != NET_MAGIC {
        return None;
    }
    Some(get_u32(bytes, 8))
}

fn net_packet(schema_id: u32, version: u16, schema_hash: u64, stride: usize, count: usize) -> Vec<u8> {
    let payload = stride.checked_mul(count).expect("net packet byte length overflows usize");
    let mut bytes = Vec::new();
    bytes.resize(NET_HEADER_BYTES + payload, 0);
    put_u32(&mut bytes, 0, NET_MAGIC);
    put_u16(&mut bytes, 4, NET_CODEC_VERSION);
    put_u32(&mut bytes, 8, schema_id);
    put_u16(&mut bytes, 12, version);
    put_u16(&mut bytes, 14, NET_HEADER_BYTES as u16);
    put_u64(&mut bytes, 16, schema_hash);
    put_u32(&mut bytes, 24, stride as u32);
    put_u32(&mut bytes, 28, u32::try_from(count).expect("net record count exceeds u32"));
    bytes
}

fn read_net_header(
    bytes: &[u8],
    schema_id: u32,
    version: u16,
    schema_hash: u64,
    stride: usize,
) -> Result<usize, NetDecodeError> {
    if bytes.len() < NET_HEADER_BYTES {
        return Err(NetDecodeError::Truncated);
    }
    if get_u32(bytes, 0) != NET_MAGIC
        || get_u16(bytes, 4) != NET_CODEC_VERSION
        || get_u32(bytes, 8) != schema_id
        || get_u16(bytes, 12) != version
        || get_u16(bytes, 14) as usize != NET_HEADER_BYTES
        || get_u64(bytes, 16) != schema_hash
        || get_u32(bytes, 24) as usize != stride
    {
        return Err(NetDecodeError::SchemaMismatch);
    }
    let count = get_u32(bytes, 28) as usize;
    match stride.checked_mul(count).and_then(|n| n.checked_add(NET_HEADER_BYTES)) {
        Some(len) if len == bytes.len() => Ok(count),
        _ => Err(NetDecodeError::InvalidLength),
    }
}

fn check_plane(actual: usize, expected: usize, name: &str) {
    assert!(actual == expected, "{} must contain exactly {} values, found {}", name, expected, actual);
}

#[inline]
fn align_up(value: usize, alignment: usize) -> usize {
    (value + alignment - 1) / alignment * alignment
}

fn vec_of<T: Copy>(len: usize, value: T) -> Vec<T> {
    let mut values = Vec::with_capacity(len);
    values.resize(len, value);
    values
}

#[inline]
fn get_bool(bytes: &[u8], at: usize) -> bool {
    bytes[at] != 0
}

#[inline]
fn put_bool(bytes: &mut [u8], at: usize, value: bool) {
    bytes[at] = value as u8;
}

${accessors}`;
}

function fieldRustType(field: NetFieldLayout, owner: string): string {
  const base = field.kind === 'struct' ? nestedName(field, owner) : rustScalar(field.type);
  return field.count === 1 ? base : `[${base}; ${field.count}]`;
}

function fieldDefault(field: NetFieldLayout, owner: string): string {
  const base =
    field.kind === 'struct' ? `${nestedName(field, owner)}::default()` : scalarDefault(field.type);
  return field.count === 1 ? base : `[${base}; ${field.count}]`;
}

/** Same naming rule as the TypeScript emitter: projections are named after their owner field. */
function nestedName(field: Extract<NetFieldLayout, { kind: 'struct' }>, owner: string): string {
  return field.struct.projectionOf ? `${owner}${capitalize(field.name)}` : field.struct.name;
}

function rustScalar(type: AoSScalarType): string {
  return type;
}

function scalarDefault(type: AoSScalarType): string {
  if (type === 'bool') return 'false';
  if (type === 'f32' || type === 'f64') return '0.0';
  return '0';
}

function scalarByteSize(type: AoSScalarType): number {
  if (type === 'bool' || type === 'i8' || type === 'u8') return 1;
  if (type === 'i16' || type === 'u16') return 2;
  if (type === 'i32' || type === 'u32' || type === 'f32') return 4;
  return 8;
}

const RUST_KEYWORDS = new Set([
  'as',
  'async',
  'await',
  'break',
  'const',
  'continue',
  'crate',
  'dyn',
  'else',
  'enum',
  'extern',
  'false',
  'fn',
  'for',
  'if',
  'impl',
  'in',
  'let',
  'loop',
  'match',
  'mod',
  'move',
  'mut',
  'pub',
  'ref',
  'return',
  'static',
  'struct',
  'trait',
  'true',
  'type',
  'unsafe',
  'use',
  'where',
  'while',
  'abstract',
  'become',
  'box',
  'do',
  'final',
  'gen',
  'macro',
  'override',
  'priv',
  'try',
  'typeof',
  'unsized',
  'virtual',
  'yield',
]);

function rustIdent(name: string): string {
  const snake = snakeCase(name);
  return RUST_KEYWORDS.has(snake) ? `r#${snake}` : snake;
}

function snakeCase(name: string): string {
  return name
    .replace(/\$/g, '_')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function constantName(name: string): string {
  return snakeCase(name).toUpperCase();
}

function capitalize(value: string): string {
  return value.length ? value[0]!.toUpperCase() + value.slice(1) : value;
}

function indent(value: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return value
    .split('\n')
    .map(line => (line ? `${prefix}${line}` : line))
    .join('\n');
}
