import {
  compileNetLayouts,
  type NetFieldLayout,
  type NetStructLayout,
  type NetStructSpec,
} from './NetLayout';

export type { NetFieldSpec, NetStructSpec, NetStructRef } from './NetLayout';

export interface EmitNetStructModuleOptions {
  banner?: string;
}

/** Emit dependency-free TypeScript views over fixed-width, batchable network records. */
export function emitNetStructModule(
  specs: readonly NetStructSpec[],
  options: EmitNetStructModuleOptions = {}
): string {
  const layouts = compileNetLayouts(specs);
  const lines = [
    options.banner ?? '// Generated by Shado. Do not edit by hand.',
    '',
    '// The 32-byte header keeps every payload naturally aligned for Wasm/GPU copies.',
    'export const NET_HEADER_BYTES = 32;',
    'export const NET_MAGIC = 0x544e5348; // "SHNT" in little-endian bytes',
    'export const NET_CODEC_VERSION = 1;',
    '',
  ];

  const declarations: string[] = [];
  const emitted = new Set<string>();
  for (const spec of specs) {
    const layout = layouts.get(spec.name)!;
    emitRecord(layout, layout.name, `${layout.name}View`, declarations, emitted);
  }
  lines.push(declarations.join('\n\n'), '');
  for (const spec of specs) lines.push(emitPacket(layouts.get(spec.name)!), '');
  lines.push(emitHelpers(), '');
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitPacket(layout: NetStructLayout): string {
  if (layout.storage === 'soa') return emitSoAPacket(layout);
  const constant = constantName(layout.name);
  return `export const ${constant}_SCHEMA_ID = ${layout.schemaId};
export const ${constant}_VERSION = ${layout.version};
export const ${constant}_STRIDE = ${layout.stride};
export const ${constant}_SCHEMA_HASH = 0x${layout.schemaHash.toString(16)}n;

export class ${layout.name}BatchView {
  readonly count: number;
  readonly payload: Uint8Array;

  constructor(readonly bytes: Uint8Array) {
    this.count = readNetHeader(
      bytes,
      ${constant}_SCHEMA_ID,
      ${constant}_VERSION,
      ${constant}_SCHEMA_HASH,
      ${constant}_STRIDE
    );
    this.payload = bytes.subarray(NET_HEADER_BYTES);
  }

  record(index: number): ${layout.name}View {
    assertRecordIndex(index, this.count);
    return new ${layout.name}View(
      this.bytes.buffer,
      this.bytes.byteOffset + NET_HEADER_BYTES + index * ${constant}_STRIDE
    );
  }
}

export function create${layout.name}Batch(
  count: number,
  target?: Uint8Array
): ${layout.name}BatchView {
  const bytes = createNetPacket(
    ${constant}_SCHEMA_ID,
    ${constant}_VERSION,
    ${constant}_SCHEMA_HASH,
    ${constant}_STRIDE,
    count,
    target
  );
  return new ${layout.name}BatchView(bytes);
}

export function view${layout.name}(
  bytes: Uint8Array,
  index = 0
): ${layout.name}View | null {
  try {
    return new ${layout.name}BatchView(bytes).record(index);
  } catch {
    return null;
  }
}

export function encode${layout.name}(
  value: Readonly<${layout.name}>,
  target?: Uint8Array
): Uint8Array {
  const batch = create${layout.name}Batch(1, target);
  write${layout.name}(batch.record(0), value);
  return batch.bytes;
}

export function decode${layout.name}(bytes: Uint8Array): ${layout.name} | null {
  const view = view${layout.name}(bytes);
  return view ? read${layout.name}(view) : null;
}`;
}

function emitSoAPacket(layout: NetStructLayout): string {
  const constant = constantName(layout.name);
  const planes = flattenSoAFields(layout);
  const descriptors = planes
    .map(
      plane =>
        `{ alignment: ${plane.alignment}, scalarBytes: ${plane.scalarBytes}, components: ${plane.components} }`
    )
    .join(',\n  ');
  const getters = planes
    .map(
      (plane, index) => `get ${plane.accessor}(): ${typedArrayName(plane.type)} {
  return new ${typedArrayName(plane.type)}(
    this.payload.buffer,
    this.payload.byteOffset + netSoAPlaneOffset(${constant}_SOA_PLANES, ${index}, this.count),
    this.count * ${plane.components}
  );
}`
    )
    .join('\n\n');
  const variants = layout.variants.length
    ? `\nexport const ${constant}_KINDS = Object.freeze({\n${layout.variants
        .map(variant => `  ${variant.name}: ${variant.tag},`)
        .join('\n')}\n});\n`
    : '';

  return `export const ${constant}_SCHEMA_ID = ${layout.schemaId};
export const ${constant}_VERSION = ${layout.version};
export const ${constant}_STRIDE = ${layout.stride};
export const ${constant}_SCHEMA_HASH = 0x${layout.schemaHash.toString(16)}n;
const ${constant}_SOA_PLANES = Object.freeze([
  ${descriptors}
]);
${variants}
export class ${layout.name}BatchView {
  readonly count: number;
  readonly payload: Uint8Array;

  constructor(readonly bytes: Uint8Array) {
    this.count = readNetHeader(
      bytes,
      ${constant}_SCHEMA_ID,
      ${constant}_VERSION,
      ${constant}_SCHEMA_HASH,
      ${constant}_STRIDE
    );
    this.payload = bytes.subarray(NET_HEADER_BYTES);
  }

${indent(getters, 2)}
}

export function create${layout.name}Batch(
  count: number,
  target?: Uint8Array
): ${layout.name}BatchView {
  return new ${layout.name}BatchView(createNetPacket(
    ${constant}_SCHEMA_ID,
    ${constant}_VERSION,
    ${constant}_SCHEMA_HASH,
    ${constant}_STRIDE,
    count,
    target
  ));
}

export function view${layout.name}Batch(bytes: Uint8Array): ${layout.name}BatchView | null {
  try { return new ${layout.name}BatchView(bytes); } catch { return null; }
}`;
}

function flattenSoAFields(
  layout: NetStructLayout,
  prefix = ''
): Array<{
  accessor: string;
  type: Extract<NetFieldLayout, { kind: 'scalar' }>['type'];
  components: number;
  alignment: number;
  scalarBytes: number;
}> {
  return layout.fields.flatMap(field => {
    const path = prefix ? `${prefix}${capitalize(field.name)}` : field.name;
    if (field.kind === 'struct') {
      if (field.count !== 1) {
        throw new Error(
          `${layout.name}.${field.name}: SoA nested arrays require an explicit schema`
        );
      }
      return flattenSoAFields(field.struct, path);
    }
    return [
      {
        accessor: path,
        type: field.type,
        components: field.count,
        alignment: field.alignment,
        scalarBytes: field.byteSize / field.count,
      },
    ];
  });
}

function emitRecord(
  layout: NetStructLayout,
  interfaceName: string,
  viewName: string,
  output: string[],
  emitted: Set<string>
): void {
  if (emitted.has(viewName)) return;
  emitted.add(viewName);

  for (const field of layout.fields) {
    if (field.kind !== 'struct') continue;
    const names = nestedNames(field, interfaceName);
    emitRecord(field.struct, names.interfaceName, names.viewName, output, emitted);
  }

  const members = layout.fields.map(
    field => `  ${field.name}: ${fieldInterfaceType(field, interfaceName)};`
  );
  const accessors = layout.fields.map(field => emitAccessor(field, interfaceName)).join('\n\n');
  const writes = layout.fields.map(field => emitObjectWrite(field, interfaceName)).join('\n');
  const reads = layout.fields.map(field => emitObjectRead(field, interfaceName)).join('\n');

  output.push(`export interface ${interfaceName} {
${members.join('\n')}
}

export class ${viewName} {
  static readonly STRIDE = ${layout.stride};

  constructor(
    readonly buffer: ArrayBufferLike,
    readonly byteOffset = 0
  ) {
    assertViewBounds(buffer, byteOffset, ${layout.stride}, '${viewName}');
  }

${indent(accessors, 2)}
}

export function write${interfaceName}(
  target: ${viewName},
  value: Readonly<${interfaceName}>
): void {
${indent(writes, 2)}
}

export function read${interfaceName}(source: ${viewName}): ${interfaceName} {
  return {
${indent(reads, 4)}
  };
}`);
}

function fieldInterfaceType(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'struct') {
    const type = nestedNames(field, owner).interfaceName;
    return field.count === 1 ? type : `readonly ${type}[]`;
  }
  const scalar = tsType(field.type);
  return field.count === 1 ? scalar : `readonly ${scalar}[]`;
}

function emitAccessor(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'struct') {
    const nested = nestedNames(field, owner);
    if (field.count === 1) {
      return `get ${field.name}(): ${nested.viewName} {
  return new ${nested.viewName}(this.buffer, this.byteOffset + ${field.byteOffset});
}`;
    }
    return `${field.name}(index: number): ${nested.viewName} {
  assertRecordIndex(index, ${field.count});
  return new ${nested.viewName}(
    this.buffer,
    this.byteOffset + ${field.byteOffset} + index * ${field.struct.stride}
  );
}`;
  }

  if (field.count > 1) {
    return `get ${field.name}(): ${typedArrayName(field.type)} {
  return new ${typedArrayName(field.type)}(
    this.buffer,
    this.byteOffset + ${field.byteOffset},
    ${field.count}
  );
}`;
  }
  const getter = scalarOperation(field.type, 'get', `this.byteOffset + ${field.byteOffset}`);
  const setter = scalarOperation(
    field.type,
    'set',
    `this.byteOffset + ${field.byteOffset}`,
    'value'
  );
  return `get ${field.name}(): ${tsType(field.type)} {
  return ${getter};
}

set ${field.name}(value: ${tsType(field.type)}) {
  ${setter};
}`;
}

function emitObjectWrite(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'struct') {
    const nested = nestedNames(field, owner);
    if (field.count === 1)
      return `write${nested.interfaceName}(target.${field.name}, value.${field.name});`;
    return `assertArrayCount(value.${field.name}, ${field.count}, '${owner}.${field.name}');
  for (let i = 0; i < ${field.count}; i++) {
    write${nested.interfaceName}(target.${field.name}(i), value.${field.name}[i]!);
  }`;
  }
  if (field.count === 1) return `target.${field.name} = value.${field.name};`;
  if (field.type === 'bool') {
    return `assertArrayCount(value.${field.name}, ${field.count}, '${owner}.${field.name}');
  for (let i = 0; i < ${field.count}; i++) target.${field.name}[i] = value.${field.name}[i] ? 1 : 0;`;
  }
  return `assertArrayCount(value.${field.name}, ${field.count}, '${owner}.${field.name}');
  target.${field.name}.set(value.${field.name});`;
}

function emitObjectRead(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'struct') {
    const nested = nestedNames(field, owner);
    if (field.count === 1)
      return `${field.name}: read${nested.interfaceName}(source.${field.name}),`;
    return `${field.name}: Array.from({ length: ${field.count} }, (_, i) =>
      read${nested.interfaceName}(source.${field.name}(i))),`;
  }
  if (field.count === 1) return `${field.name}: source.${field.name},`;
  if (field.type === 'bool')
    return `${field.name}: Array.from(source.${field.name}, value => value !== 0),`;
  return `${field.name}: Array.from(source.${field.name}),`;
}

function nestedNames(field: Extract<NetFieldLayout, { kind: 'struct' }>, owner: string) {
  if (!field.struct.projectionOf) {
    return { interfaceName: field.struct.name, viewName: `${field.struct.name}View` };
  }
  const interfaceName = `${owner}${capitalize(field.name)}`;
  return { interfaceName, viewName: `${interfaceName}View` };
}

function scalarOperation(
  type: Extract<NetFieldLayout, { kind: 'scalar' }>['type'],
  operation: 'get' | 'set',
  offset: string,
  value?: string
): string {
  const args =
    operation === 'set' ? `${offset}, ${type === 'bool' ? `${value} ? 1 : 0` : value}` : offset;
  const littleEndian = scalarByteSize(type) > 1 ? ', true' : '';
  const suffix = scalarDataViewSuffix(type);
  const call = `new DataView(this.buffer).${operation}${suffix}(${args}${littleEndian})`;
  return type === 'bool' && operation === 'get' ? `${call} !== 0` : call;
}

function emitHelpers(): string {
  return `function createNetPacket(
  schemaId: number,
  version: number,
  schemaHash: bigint,
  stride: number,
  count: number,
  target?: Uint8Array
): Uint8Array {
  if (!Number.isSafeInteger(count) || count < 0) throw new RangeError('net record count must be a non-negative safe integer');
  const byteLength = NET_HEADER_BYTES + stride * count;
  if (!Number.isSafeInteger(byteLength)) throw new RangeError('net packet byte length exceeds the safe integer range');
  const bytes = target ? target.subarray(0, byteLength) : new Uint8Array(byteLength);
  if (bytes.byteLength !== byteLength) throw new RangeError('target is too small for the net packet');
  bytes.fill(0);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  view.setUint32(0, NET_MAGIC, true);
  view.setUint16(4, NET_CODEC_VERSION, true);
  view.setUint32(8, schemaId, true);
  view.setUint16(12, version, true);
  view.setUint16(14, NET_HEADER_BYTES, true);
  view.setBigUint64(16, schemaHash, true);
  view.setUint32(24, stride, true);
  view.setUint32(28, count, true);
  return bytes;
}

function readNetHeader(
  bytes: Uint8Array,
  schemaId: number,
  version: number,
  schemaHash: bigint,
  stride: number
): number {
  if (bytes.byteLength < NET_HEADER_BYTES) throw new RangeError('truncated net header');
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (
    view.getUint32(0, true) !== NET_MAGIC ||
    view.getUint16(4, true) !== NET_CODEC_VERSION ||
    view.getUint32(8, true) !== schemaId ||
    view.getUint16(12, true) !== version ||
    view.getUint16(14, true) !== NET_HEADER_BYTES ||
    view.getBigUint64(16, true) !== schemaHash ||
    view.getUint32(24, true) !== stride
  ) throw new TypeError('net schema or ABI mismatch');
  const count = view.getUint32(28, true);
  if (bytes.byteLength !== NET_HEADER_BYTES + stride * count) throw new RangeError('invalid net payload length');
  return count;
}

function assertViewBounds(buffer: ArrayBufferLike, byteOffset: number, stride: number, name: string): void {
  if (!Number.isSafeInteger(byteOffset) || byteOffset < 0 || byteOffset + stride > buffer.byteLength) {
    throw new RangeError(name + ' exceeds its backing buffer');
  }
}

function assertRecordIndex(index: number, count: number): void {
  if (!Number.isSafeInteger(index) || index < 0 || index >= count) throw new RangeError('net record index out of bounds');
}

function assertArrayCount(value: readonly unknown[], count: number, name: string): void {
  if (value.length !== count) throw new RangeError(name + ' must contain exactly ' + count + ' values');
}

function netSoAPlaneOffset(
  planes: readonly { alignment: number; scalarBytes: number; components: number }[],
  planeIndex: number,
  count: number
): number {
  let offset = 0;
  for (let i = 0; i < planeIndex; i++) {
    const plane = planes[i]!;
    offset = Math.ceil(offset / plane.alignment) * plane.alignment;
    offset += plane.scalarBytes * plane.components * count;
  }
  const plane = planes[planeIndex]!;
  return Math.ceil(offset / plane.alignment) * plane.alignment;
}`;
}

function typedArrayName(type: Extract<NetFieldLayout, { kind: 'scalar' }>['type']): string {
  switch (type) {
    case 'bool':
    case 'u8':
      return 'Uint8Array';
    case 'i8':
      return 'Int8Array';
    case 'u16':
      return 'Uint16Array';
    case 'i16':
      return 'Int16Array';
    case 'u32':
      return 'Uint32Array';
    case 'i32':
      return 'Int32Array';
    case 'f32':
      return 'Float32Array';
    case 'u64':
      return 'BigUint64Array';
    case 'i64':
      return 'BigInt64Array';
    case 'f64':
      return 'Float64Array';
  }
}

function scalarDataViewSuffix(type: Extract<NetFieldLayout, { kind: 'scalar' }>['type']): string {
  switch (type) {
    case 'bool':
    case 'u8':
      return 'Uint8';
    case 'i8':
      return 'Int8';
    case 'u16':
      return 'Uint16';
    case 'i16':
      return 'Int16';
    case 'u32':
      return 'Uint32';
    case 'i32':
      return 'Int32';
    case 'f32':
      return 'Float32';
    case 'u64':
      return 'BigUint64';
    case 'i64':
      return 'BigInt64';
    case 'f64':
      return 'Float64';
  }
}

function scalarByteSize(type: Extract<NetFieldLayout, { kind: 'scalar' }>['type']): number {
  if (type === 'bool' || type === 'i8' || type === 'u8') return 1;
  if (type === 'i16' || type === 'u16') return 2;
  if (type === 'i32' || type === 'u32' || type === 'f32') return 4;
  return 8;
}

function tsType(
  type: Extract<NetFieldLayout, { kind: 'scalar' }>['type']
): 'number' | 'bigint' | 'boolean' {
  if (type === 'bool') return 'boolean';
  if (type === 'i64' || type === 'u64') return 'bigint';
  return 'number';
}

function constantName(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function capitalize(value: string): string {
  return value.length ? value[0]!.toUpperCase() + value.slice(1) : value;
}

function indent(value: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return value
    .split('\n')
    .map(line => `${prefix}${line}`)
    .join('\n');
}
