import type { AoSScalarType } from '../schema/AoSLayout';
import {
  compileNetLayouts,
  type NetFieldLayout,
  type NetStructLayout,
  type NetVarFieldLayout,
  type NetStructSpec,
} from './NetLayout';

export interface EmitNetStructRustModuleOptions {
  banner?: string;
  /**
   * Where `Vec` comes from. `alloc` suits `#![no_std]` crates that declare
   * `extern crate alloc` at their root; `std` is the default.
   */
  vec?: 'std' | 'alloc';
}

/**
 * Emit a dependency-free Rust module whose packets are byte-identical to the
 * ones `emitNetStructModule` produces from the same specs: the same 32-byte
 * header, schema hashes, record strides and SoA plane placement.
 *
 * Fixed records are owned `Copy` values. Records with variable-length fields
 * get two types: `Name<'a>`, which borrows its strings and lists for writing,
 * and `NameView<'a>`, which reads a validated packet in place. Neither
 * allocates; `encode_into` reuses the caller's buffer. Every read and write is
 * an explicit little-endian copy at a compiled offset, so the module needs no
 * `unsafe` and does not depend on Rust's own struct layout.
 */
export function emitNetStructRustModule(
  specs: readonly NetStructSpec[],
  options: EmitNetStructRustModuleOptions = {}
): string {
  const layouts = compileNetLayouts(specs);
  const variable = [...layouts.values()].some(layout => layout.variable);
  const vec = options.vec === 'alloc' ? 'alloc::vec::Vec' : 'std::vec::Vec';
  const lines = [
    options.banner ?? '// Generated by Shado. Do not edit by hand.',
    '',
    '#![allow(dead_code, clippy::all)]',
    '',
    `use ${vec};`,
    '',
    '// The 32-byte header keeps every payload naturally aligned for Wasm/GPU copies.',
    'pub const NET_HEADER_BYTES: usize = 32;',
    'pub const NET_MAGIC: u32 = 0x544e5348; // "SHNT" in little-endian bytes',
    'pub const NET_CODEC_VERSION: u16 = 1;',
    '',
    emitRuntime(),
    '',
    ...(variable ? [emitHeapRuntime(), ''] : []),
  ];

  const declarations: string[] = [];
  const emitted = new Set<string>();
  for (const spec of specs) {
    const layout = layouts.get(spec.name)!;
    emitRecord(layout, layout.name, declarations, emitted, variable);
  }
  lines.push(declarations.join('\n\n'), '');
  for (const spec of specs) lines.push(emitPacket(layouts.get(spec.name)!), '');
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitPacket(layout: NetStructLayout): string {
  const constant = constantName(layout.name);
  const header = `pub const ${constant}_SCHEMA_ID: u32 = 0x${layout.schemaId.toString(16)};
pub const ${constant}_VERSION: u16 = ${layout.version};
pub const ${constant}_STRIDE: usize = ${layout.stride};
pub const ${constant}_SCHEMA_HASH: u64 = 0x${layout.schemaHash.toString(16)};`;
  if (layout.storage === 'soa') return `${header}\n\n${emitSoABatch(layout, constant)}`;
  if (layout.variable) {
    return `${header}

impl<'a> NetMessagePacket for ${layout.name}<'a> {
    const SCHEMA_ID: u32 = ${constant}_SCHEMA_ID;
    const VERSION: u16 = ${constant}_VERSION;
    const SCHEMA_HASH: u64 = ${constant}_SCHEMA_HASH;
}

impl<'a> NetMessageView<'a> for ${layout.name}View<'a> {
    const SCHEMA_ID: u32 = ${constant}_SCHEMA_ID;
    const VERSION: u16 = ${constant}_VERSION;
    const SCHEMA_HASH: u64 = ${constant}_SCHEMA_HASH;
}`;
  }
  return `${header}

impl NetPacket for ${layout.name} {
    const SCHEMA_ID: u32 = ${constant}_SCHEMA_ID;
    const VERSION: u16 = ${constant}_VERSION;
    const SCHEMA_HASH: u64 = ${constant}_SCHEMA_HASH;
}`;
}

function emitRecord(
  layout: NetStructLayout,
  typeName: string,
  output: string[],
  emitted: Set<string>,
  elements: boolean
): void {
  if (emitted.has(typeName)) return;
  emitted.add(typeName);

  for (const field of layout.fields) {
    const struct = field.kind === 'scalar' ? undefined : field.struct;
    if (!struct) continue;
    emitRecord(struct, nestedName(field.name, struct, typeName), output, emitted, elements);
  }
  if (layout.variable) {
    output.push(emitMessageRecord(layout, typeName));
    return;
  }

  const members = layout.fields.map(
    field => `    pub ${rustIdent(field.name)}: ${fieldRustType(field, typeName)},`
  );
  const defaults = layout.fields.map(
    field => `            ${rustIdent(field.name)}: ${fieldDefault(field, typeName)},`
  );
  const writes = layout.fields.map(emitFieldWrite);
  const reads = layout.fields.map(field => emitFieldRead(field, typeName));
  const kinds = layout.variants.length ? emitKinds(layout, typeName) : '';
  const element = elements
    ? `

impl<'a> NetElement<'a> for ${typeName} {
    const SIZE: usize = ${layout.stride};

    fn read_element(bytes: &'a [u8], _heap: &'a [u8]) -> Self {
        Self::read_record(bytes)
    }
}`
    : '';

  output.push(`#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ${typeName} {
${members.join('\n')}
}

impl Default for ${typeName} {
    fn default() -> Self {
        Self {
${defaults.join('\n')}
        }
    }
}

impl NetRecord for ${typeName} {
    const STRIDE: usize = ${layout.stride};

    fn write_record(&self, out: &mut [u8]) {
${writes.map(line => indent(line, 8)).join('\n')}
    }

    fn read_record(bytes: &[u8]) -> Self {
        Self {
${reads.map(line => indent(line, 12)).join('\n')}
        }
    }
}${element}${kinds}`);
}

function emitKinds(layout: NetStructLayout, typeName: string, lifetime = ''): string {
  const kind = layout.fields.find(field => field.name === 'kind')!;
  const type = kind.kind === 'scalar' ? rustScalar(kind.type) : 'u32';
  const constants = layout.variants.map(
    variant => `    pub const KIND_${constantName(variant.name)}: ${type} = ${variant.tag};`
  );
  return `

impl${lifetime} ${typeName}${lifetime} {
${constants.join('\n')}
}`;
}

function emitFieldWrite(field: NetFieldLayout): string {
  const name = rustIdent(field.name);
  if (field.kind === 'var') throw new Error(`${field.name}: variable fields need a message record`);
  if (field.kind === 'struct') {
    const stride = field.struct.stride;
    if (field.count === 1) {
      return `self.${name}.write_record(&mut out[${field.byteOffset}..${field.byteOffset + stride}]);`;
    }
    return `for (i, item) in self.${name}.iter().enumerate() {
    let at = ${field.byteOffset} + i * ${stride};
    item.write_record(&mut out[at..at + ${stride}]);
}`;
  }
  const size = scalarByteSize(field.type);
  const put = `put_${field.type}`;
  if (field.count === 1) return `${put}(out, ${field.byteOffset}, self.${name});`;
  return `for (i, value) in self.${name}.iter().enumerate() {
    ${put}(out, ${field.byteOffset} + i * ${size}, *value);
}`;
}

function emitFieldRead(field: NetFieldLayout, owner: string): string {
  const name = rustIdent(field.name);
  if (field.kind === 'var') throw new Error(`${field.name}: variable fields need a message record`);
  if (field.kind === 'struct') {
    const nested = nestedName(field.name, field.struct, owner);
    const stride = field.struct.stride;
    if (field.count === 1) {
      return `${name}: ${nested}::read_record(&bytes[${field.byteOffset}..${field.byteOffset + stride}]),`;
    }
    return `${name}: core::array::from_fn(|i| {
    let at = ${field.byteOffset} + i * ${stride};
    ${nested}::read_record(&bytes[at..at + ${stride}])
}),`;
  }
  const get = `get_${field.type}`;
  if (field.count === 1) return `${name}: ${get}(bytes, ${field.byteOffset}),`;
  return `${name}: core::array::from_fn(|i| ${get}(bytes, ${field.byteOffset} + i * ${scalarByteSize(field.type)})),`;
}

interface RustSoAPlane {
  /** Batch member name, e.g. `state_position`. */
  member: string;
  /** Path to the value inside one row, e.g. `state.position`. */
  rowPath: string;
  type: AoSScalarType;
  components: number;
  alignment: number;
  scalarBytes: number;
}

function flattenSoAPlanes(layout: NetStructLayout, prefix = '', rowPrefix = ''): RustSoAPlane[] {
  return layout.fields.flatMap(field => {
    const member = prefix ? `${prefix}_${snakeCase(field.name)}` : snakeCase(field.name);
    const rowPath = rowPrefix ? `${rowPrefix}.${rustIdent(field.name)}` : rustIdent(field.name);
    if (field.kind === 'var') {
      throw new Error(
        `${layout.name}.${field.name}: SoA planes cannot hold variable-length fields`
      );
    }
    if (field.kind === 'struct') {
      if (field.count !== 1) {
        throw new Error(
          `${layout.name}.${field.name}: SoA nested arrays require an explicit schema`
        );
      }
      return flattenSoAPlanes(field.struct, member, rowPath);
    }
    return [
      {
        member,
        rowPath,
        type: field.type,
        components: field.count,
        alignment: field.alignment,
        scalarBytes: field.byteSize / field.count,
      },
    ];
  });
}

function emitSoABatch(layout: NetStructLayout, constant: string): string {
  const batch = `${layout.name}Batch`;
  const planes = flattenSoAPlanes(layout);
  const members = planes.map(
    plane =>
      `    /// ${plane.components === 1 ? 'One value per row.' : `${plane.components} values per row, row-major.`}\n    pub ${rustIdent(plane.member)}: Vec<${rustScalar(plane.type)}>,`
  );
  const zeroed = planes.map(
    plane =>
      `            ${rustIdent(plane.member)}: vec_of(count * ${plane.components}, ${scalarDefault(plane.type)}),`
  );
  const encode = planes.map(plane => {
    const member = rustIdent(plane.member);
    return `at = align_up(at, ${plane.alignment});
check_plane(self.${member}.len(), self.count * ${plane.components}, "${layout.name}.${plane.member}");
for (i, value) in self.${member}.iter().enumerate() {
    put_${plane.type}(payload, at + i * ${plane.scalarBytes}, *value);
}
at += ${plane.scalarBytes * plane.components} * self.count;`;
  });
  const decode = planes.map(plane => {
    const member = rustIdent(plane.member);
    return `at = align_up(at, ${plane.alignment});
let mut ${member} = Vec::with_capacity(count * ${plane.components});
for i in 0..count * ${plane.components} {
    ${member}.push(get_${plane.type}(payload, at + i * ${plane.scalarBytes}));
}
at += ${plane.scalarBytes * plane.components} * count;`;
  });
  const memberList = planes.map(plane => `            ${rustIdent(plane.member)},`);
  const rowReads = planes.map(plane => {
    const member = rustIdent(plane.member);
    if (plane.components === 1) return `row.${plane.rowPath} = self.${member}[index];`;
    return `row.${plane.rowPath}.copy_from_slice(&self.${member}[index * ${plane.components}..(index + 1) * ${plane.components}]);`;
  });
  const rowWrites = planes.map(plane => {
    const member = rustIdent(plane.member);
    if (plane.components === 1) return `self.${member}[index] = row.${plane.rowPath};`;
    return `self.${member}[index * ${plane.components}..(index + 1) * ${plane.components}].copy_from_slice(&row.${plane.rowPath});`;
  });

  return `/// Column-major batch of \`${layout.name}\` rows: one plane per scalar field,
/// laid out back to back in the payload exactly as the TypeScript view reads it.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ${batch} {
    pub count: usize,
${members.join('\n')}
}

impl ${batch} {
    pub const SCHEMA_ID: u32 = ${constant}_SCHEMA_ID;
    pub const VERSION: u16 = ${constant}_VERSION;
    pub const STRIDE: usize = ${constant}_STRIDE;
    pub const SCHEMA_HASH: u64 = ${constant}_SCHEMA_HASH;

    /// A batch of \`count\` zeroed rows.
    pub fn with_count(count: usize) -> Self {
        Self {
            count,
${zeroed.join('\n')}
        }
    }

    pub fn from_rows(rows: &[${layout.name}]) -> Self {
        let mut batch = Self::with_count(rows.len());
        for (index, row) in rows.iter().enumerate() {
            batch.set_row(index, row);
        }
        batch
    }

    pub fn row(&self, index: usize) -> ${layout.name} {
        let mut row = ${layout.name}::default();
${rowReads.map(line => indent(line, 8)).join('\n')}
        row
    }

    pub fn set_row(&mut self, index: usize, row: &${layout.name}) {
${rowWrites.map(line => indent(line, 8)).join('\n')}
    }

    pub fn encode(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        self.encode_into(&mut bytes);
        bytes
    }

    /// Encode into \`out\`, replacing its contents and reusing its capacity.
    pub fn encode_into(&self, bytes: &mut Vec<u8>) {
        net_packet_into(
            bytes,
            Self::SCHEMA_ID,
            Self::VERSION,
            Self::SCHEMA_HASH,
            Self::STRIDE,
            self.count,
            Self::STRIDE * self.count,
        );
        let payload = &mut bytes[NET_HEADER_BYTES..];
        let mut at = 0usize;
${encode.map(line => indent(line, 8)).join('\n')}
        let _ = at;
    }

    pub fn decode(bytes: &[u8]) -> Result<Self, NetDecodeError> {
        let count = read_net_header(
            bytes,
            Self::SCHEMA_ID,
            Self::VERSION,
            Self::SCHEMA_HASH,
            Self::STRIDE,
        )?;
        let payload = &bytes[NET_HEADER_BYTES..];
        let mut at = 0usize;
${decode.map(line => indent(line, 8)).join('\n')}
        let _ = at;
        Ok(Self {
            count,
${memberList.join('\n')}
        })
    }
}`;
}

function emitRuntime(): string {
  const scalars: AoSScalarType[] = [
    'i8',
    'u8',
    'i16',
    'u16',
    'i32',
    'u32',
    'f32',
    'i64',
    'u64',
    'f64',
  ];
  const accessors = scalars
    .map(type => {
      const size = scalarByteSize(type);
      return `#[inline]
fn get_${type}(bytes: &[u8], at: usize) -> ${type} {
    let mut raw = [0u8; ${size}];
    raw.copy_from_slice(&bytes[at..at + ${size}]);
    ${type}::from_le_bytes(raw)
}

#[inline]
fn put_${type}(bytes: &mut [u8], at: usize, value: ${type}) {
    bytes[at..at + ${size}].copy_from_slice(&value.to_le_bytes());
}`;
    })
    .join('\n\n');

  return `#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NetDecodeError {
    /** Fewer bytes than a header. */
    Truncated,
    /** Magic, codec version, schema id, schema version, header size, hash or stride differ. */
    SchemaMismatch,
    /** The payload is not exactly \`stride * count\` bytes. */
    InvalidLength,
    /** A single-record decode found an empty batch. */
    Empty,
    /** A variable-length field points outside the heap. */
    HeapOutOfBounds,
    /** A string field is not UTF-8. */
    InvalidUtf8,
    /** Heap references add up to more than the traversal budget allows. */
    TraversalLimit,
}

/// One fixed-width record, written at the offsets the schema compiled to.
pub trait NetRecord: Sized {
    const STRIDE: usize;
    /// Write into \`out\`, which is exactly \`STRIDE\` bytes and already zeroed.
    fn write_record(&self, out: &mut [u8]);
    /// Read from \`bytes\`, which is exactly \`STRIDE\` bytes.
    fn read_record(bytes: &[u8]) -> Self;
}

/// A record with its own packet identity, sent as an array-of-structs batch.
pub trait NetPacket: NetRecord {
    const SCHEMA_ID: u32;
    const VERSION: u16;
    const SCHEMA_HASH: u64;

    fn encode(&self) -> Vec<u8> {
        encode_net_batch(core::slice::from_ref(self))
    }

    /// Encode into \`out\`, replacing its contents and reusing its capacity.
    fn encode_into(&self, out: &mut Vec<u8>) {
        encode_net_batch_into(core::slice::from_ref(self), out)
    }

    /// The first record of a packet, like the TypeScript \`decode*\` helpers.
    fn decode(bytes: &[u8]) -> Result<Self, NetDecodeError> {
        let count = read_net_header(bytes, Self::SCHEMA_ID, Self::VERSION, Self::SCHEMA_HASH, Self::STRIDE)?;
        if count == 0 {
            return Err(NetDecodeError::Empty);
        }
        Ok(Self::read_record(&bytes[NET_HEADER_BYTES..NET_HEADER_BYTES + Self::STRIDE]))
    }
}

pub fn encode_net_batch<T: NetPacket>(records: &[T]) -> Vec<u8> {
    let mut bytes = Vec::new();
    encode_net_batch_into(records, &mut bytes);
    bytes
}

pub fn encode_net_batch_into<T: NetPacket>(records: &[T], out: &mut Vec<u8>) {
    let payload = T::STRIDE.checked_mul(records.len()).expect("net packet byte length overflows usize");
    net_packet_into(out, T::SCHEMA_ID, T::VERSION, T::SCHEMA_HASH, T::STRIDE, records.len(), payload);
    for (i, record) in records.iter().enumerate() {
        let at = NET_HEADER_BYTES + i * T::STRIDE;
        record.write_record(&mut out[at..at + T::STRIDE]);
    }
}

pub fn decode_net_batch<T: NetPacket>(bytes: &[u8]) -> Result<Vec<T>, NetDecodeError> {
    let count = read_net_header(bytes, T::SCHEMA_ID, T::VERSION, T::SCHEMA_HASH, T::STRIDE)?;
    let mut records = Vec::with_capacity(count);
    for i in 0..count {
        let at = NET_HEADER_BYTES + i * T::STRIDE;
        records.push(T::read_record(&bytes[at..at + T::STRIDE]));
    }
    Ok(records)
}

/// The schema id of a packet without validating the rest of it, for routing.
pub fn peek_net_schema_id(bytes: &[u8]) -> Option<u32> {
    if bytes.len() < NET_HEADER_BYTES || get_u32(bytes, 0) != NET_MAGIC {
        return None;
    }
    Some(get_u32(bytes, 8))
}

fn net_packet_into(
    bytes: &mut Vec<u8>,
    schema_id: u32,
    version: u16,
    schema_hash: u64,
    stride: usize,
    count: usize,
    payload: usize,
) {
    bytes.clear();
    bytes.resize(NET_HEADER_BYTES + payload, 0);
    put_u32(bytes, 0, NET_MAGIC);
    put_u16(bytes, 4, NET_CODEC_VERSION);
    put_u32(bytes, 8, schema_id);
    put_u16(bytes, 12, version);
    put_u16(bytes, 14, NET_HEADER_BYTES as u16);
    put_u64(bytes, 16, schema_hash);
    put_u32(bytes, 24, stride as u32);
    put_u32(bytes, 28, u32::try_from(count).expect("net record count exceeds u32"));
}

fn read_net_header(
    bytes: &[u8],
    schema_id: u32,
    version: u16,
    schema_hash: u64,
    stride: usize,
) -> Result<usize, NetDecodeError> {
    if bytes.len() < NET_HEADER_BYTES {
        return Err(NetDecodeError::Truncated);
    }
    if get_u32(bytes, 0) != NET_MAGIC
        || get_u16(bytes, 4) != NET_CODEC_VERSION
        || get_u32(bytes, 8) != schema_id
        || get_u16(bytes, 12) != version
        || get_u16(bytes, 14) as usize != NET_HEADER_BYTES
        || get_u64(bytes, 16) != schema_hash
        || get_u32(bytes, 24) as usize != stride
    {
        return Err(NetDecodeError::SchemaMismatch);
    }
    let count = get_u32(bytes, 28) as usize;
    match stride.checked_mul(count).and_then(|n| n.checked_add(NET_HEADER_BYTES)) {
        Some(len) if len == bytes.len() => Ok(count),
        _ => Err(NetDecodeError::InvalidLength),
    }
}

fn check_plane(actual: usize, expected: usize, name: &str) {
    assert!(actual == expected, "{} must contain exactly {} values, found {}", name, expected, actual);
}

#[inline]
fn align_up(value: usize, alignment: usize) -> usize {
    (value + alignment - 1) / alignment * alignment
}

fn vec_of<T: Copy>(len: usize, value: T) -> Vec<T> {
    let mut values = Vec::with_capacity(len);
    values.resize(len, value);
    values
}

#[inline]
fn get_bool(bytes: &[u8], at: usize) -> bool {
    bytes[at] != 0
}

#[inline]
fn put_bool(bytes: &mut [u8], at: usize, value: bool) {
    bytes[at] = value as u8;
}

${accessors}`;
}

function fieldRustType(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'var') throw new Error(`${field.name}: variable fields need a message record`);
  const base =
    field.kind === 'struct' ? nestedName(field.name, field.struct, owner) : rustScalar(field.type);
  return field.count === 1 ? base : `[${base}; ${field.count}]`;
}

function fieldDefault(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'var') throw new Error(`${field.name}: variable fields need a message record`);
  const base =
    field.kind === 'struct'
      ? `${nestedName(field.name, field.struct, owner)}::default()`
      : scalarDefault(field.type);
  return field.count === 1 ? base : `[${base}; ${field.count}]`;
}

/** Same naming rule as the TypeScript emitter: projections are named after their owner field. */
function nestedName(fieldName: string, struct: NetStructLayout, owner: string): string {
  return struct.projectionOf ? `${owner}${capitalize(fieldName)}` : struct.name;
}

/** Rust type of one field in the borrowed writer struct `Name<'a>`. */
function messageFieldType(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'var') {
    if (field.varKind === 'str') return `&'a str`;
    if (field.varKind === 'bytes') return `&'a [u8]`;
    if (field.varKind === 'scalarList') return `&'a [${rustScalar(field.element!)}]`;
    return `&'a [${recordType(field.name, field.struct!, owner)}]`;
  }
  if (field.kind === 'struct') {
    const base = recordType(field.name, field.struct, owner);
    return field.count === 1 ? base : `[${base}; ${field.count}]`;
  }
  const base = rustScalar(field.type);
  return field.count === 1 ? base : `[${base}; ${field.count}]`;
}

function messageFieldDefault(field: NetFieldLayout, owner: string): string {
  if (field.kind === 'var') return field.varKind === 'str' ? '""' : '&[]';
  const base =
    field.kind === 'struct'
      ? `${nestedName(field.name, field.struct, owner)}::default()`
      : scalarDefault(field.type);
  return field.count === 1 ? base : `[${base}; ${field.count}]`;
}

/** `Name` for fixed records, `Name<'a>` for records that borrow heap data. */
function recordType(fieldName: string, struct: NetStructLayout, owner: string): string {
  const name = nestedName(fieldName, struct, owner);
  return struct.variable ? `${name}<'a>` : name;
}

function viewType(fieldName: string, struct: NetStructLayout, owner: string): string {
  return `${nestedName(fieldName, struct, owner)}View<'a>`;
}

/** The list element a reader sees: fixed records by value, variable ones as views. */
function elementType(fieldName: string, struct: NetStructLayout, owner: string): string {
  return struct.variable
    ? viewType(fieldName, struct, owner)
    : nestedName(fieldName, struct, owner);
}

function emitMessageWrite(field: NetFieldLayout): string {
  const name = rustIdent(field.name);
  const slot = `at + ${field.byteOffset}`;
  if (field.kind === 'scalar') {
    const put = `put_${field.type}`;
    if (field.count === 1) return `${put}(buf, ${slot}, self.${name});`;
    return `for (i, value) in self.${name}.iter().enumerate() {
    ${put}(buf, ${slot} + i * ${scalarByteSize(field.type)}, *value);
}`;
  }
  if (field.kind === 'struct') {
    const stride = field.struct.stride;
    const write = (item: string, offset: string) =>
      field.struct.variable
        ? `${item}.write_message(buf, ${offset}, heap, cursor);`
        : `${item}.write_record(&mut buf[${offset}..${offset} + ${stride}]);`;
    if (field.count === 1) return write(`self.${name}`, slot);
    return `for (i, item) in self.${name}.iter().enumerate() {
    ${write('item', `${slot} + i * ${stride}`)}
}`;
  }
  return emitVarMessageWrite(field, name, slot);
}

function emitVarMessageWrite(field: NetVarFieldLayout, name: string, slot: string): string {
  if (field.varKind === 'str' || field.varKind === 'bytes') {
    const bytes = field.varKind === 'str' ? `self.${name}.as_bytes()` : `self.${name}`;
    return `{
    let bytes = ${bytes};
    let to = net_reserve(buf, ${slot}, heap, cursor, bytes.len(), 1, 1);
    buf[to..to + bytes.len()].copy_from_slice(bytes);
}`;
  }
  if (field.varKind === 'scalarList') {
    const size = field.elementSize;
    return `{
    let to = net_reserve(buf, ${slot}, heap, cursor, self.${name}.len(), ${size}, ${size});
    for (i, value) in self.${name}.iter().enumerate() {
        put_${field.element}(buf, to + i * ${size}, *value);
    }
}`;
  }
  const struct = field.struct!;
  const stride = struct.stride;
  const write = struct.variable
    ? `item.write_message(buf, to + i * ${stride}, heap, cursor);`
    : `item.write_record(&mut buf[to + i * ${stride}..to + (i + 1) * ${stride}]);`;
  return `{
    let to = net_reserve(buf, ${slot}, heap, cursor, self.${name}.len(), ${stride}, ${struct.alignment});
    for (i, item) in self.${name}.iter().enumerate() {
        ${write}
    }
}`;
}

/** Heap bytes, in exactly the order `write_message` reserves them. */
function emitMessageMeasure(field: NetFieldLayout): string[] {
  const name = rustIdent(field.name);
  if (field.kind === 'scalar') return [];
  if (field.kind === 'struct') {
    if (!field.struct.variable) return [];
    if (field.count === 1) return [`cursor = self.${name}.measure(cursor);`];
    return [`for item in self.${name}.iter() {\n    cursor = item.measure(cursor);\n}`];
  }
  if (field.varKind === 'str') return [`cursor = net_measure(cursor, self.${name}.len(), 1, 1);`];
  if (field.varKind === 'bytes') return [`cursor = net_measure(cursor, self.${name}.len(), 1, 1);`];
  if (field.varKind === 'scalarList') {
    return [
      `cursor = net_measure(cursor, self.${name}.len(), ${field.elementSize}, ${field.elementSize});`,
    ];
  }
  const struct = field.struct!;
  const reserve = `cursor = net_measure(cursor, self.${name}.len(), ${struct.stride}, ${struct.alignment});`;
  if (!struct.variable) return [reserve];
  return [reserve, `for item in self.${name}.iter() {\n    cursor = item.measure(cursor);\n}`];
}

function emitViewAccessor(field: NetFieldLayout, owner: string): string {
  const name = rustIdent(field.name);
  const offset = field.byteOffset;
  if (field.kind === 'scalar') {
    const type = rustScalar(field.type);
    if (field.count === 1) {
      return `pub fn ${name}(&self) -> ${type} {
    get_${field.type}(self.record, ${offset})
}`;
    }
    return `pub fn ${name}(&self) -> [${type}; ${field.count}] {
    core::array::from_fn(|i| get_${field.type}(self.record, ${offset} + i * ${scalarByteSize(field.type)}))
}`;
  }
  if (field.kind === 'struct') {
    const stride = field.struct.stride;
    const type = elementType(field.name, field.struct, owner);
    const read = (at: string) =>
      field.struct.variable
        ? `${nestedName(field.name, field.struct, owner)}View::from_parts(&self.record[${at}..${at} + ${stride}], self.heap)`
        : `${type}::read_record(&self.record[${at}..${at} + ${stride}])`;
    if (field.count === 1) {
      return `pub fn ${name}(&self) -> ${type} {
    ${read(String(offset))}
}`;
    }
    return `pub fn ${name}(&self) -> [${type}; ${field.count}] {
    core::array::from_fn(|i| {
        let at = ${offset} + i * ${stride};
        ${read('at')}
    })
}`;
  }
  if (field.varKind === 'str') {
    return `pub fn ${name}(&self) -> &'a str {
    net_heap_str(self.record, ${offset}, self.heap)
}`;
  }
  if (field.varKind === 'bytes') {
    return `pub fn ${name}(&self) -> &'a [u8] {
    net_heap_bytes(self.record, ${offset}, self.heap)
}`;
  }
  const element =
    field.varKind === 'scalarList'
      ? rustScalar(field.element!)
      : elementType(field.name, field.struct!, owner);
  return `pub fn ${name}(&self) -> NetList<'a, ${element}> {
    net_list(self.record, ${offset}, self.heap)
}`;
}

function emitViewValidate(field: NetFieldLayout, owner: string): string[] {
  const offset = field.byteOffset;
  if (field.kind === 'scalar') return [];
  if (field.kind === 'struct') {
    if (!field.struct.variable) return [];
    const view = `${nestedName(field.name, field.struct, owner)}View`;
    const stride = field.struct.stride;
    if (field.count === 1) {
      return [`${view}::validate(&record[${offset}..${offset + stride}], heap, budget)?;`];
    }
    return [
      `for i in 0..${field.count} {
    let at = ${offset} + i * ${stride};
    ${view}::validate(&record[at..at + ${stride}], heap, budget)?;
}`,
    ];
  }
  if (field.varKind === 'str') {
    return [
      `{
    let (start, len) = net_validate_slot(record, ${offset}, heap, 1, budget)?;
    core::str::from_utf8(&heap[start..start + len]).map_err(|_| NetDecodeError::InvalidUtf8)?;
}`,
    ];
  }
  if (field.varKind !== 'structList' || !field.struct!.variable) {
    return [`net_validate_slot(record, ${offset}, heap, ${field.elementSize}, budget)?;`];
  }
  const struct = field.struct!;
  const view = `${nestedName(field.name, struct, owner)}View`;
  return [
    `{
    let (start, len) = net_validate_slot(record, ${offset}, heap, ${struct.stride}, budget)?;
    for i in 0..len {
        let at = start + i * ${struct.stride};
        ${view}::validate(&heap[at..at + ${struct.stride}], heap, budget)?;
    }
}`,
  ];
}

function emitMessageRecord(layout: NetStructLayout, typeName: string): string {
  const members = layout.fields.map(
    field => `    pub ${rustIdent(field.name)}: ${messageFieldType(field, typeName)},`
  );
  const defaults = layout.fields.map(
    field => `            ${rustIdent(field.name)}: ${messageFieldDefault(field, typeName)},`
  );
  const writes = layout.fields.map(emitMessageWrite);
  const measures = layout.fields.flatMap(emitMessageMeasure);
  const accessors = layout.fields.map(field => emitViewAccessor(field, typeName));
  const validates = layout.fields.flatMap(field => emitViewValidate(field, typeName));
  const kinds = layout.variants.length ? emitKinds(layout, typeName, "<'a>") : '';

  return `/// Writer side of \`${typeName}\`: borrows its strings and lists, so building one
/// allocates nothing.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ${typeName}<'a> {
${members.join('\n')}
}

impl<'a> Default for ${typeName}<'a> {
    fn default() -> Self {
        Self {
${defaults.join('\n')}
        }
    }
}

impl<'a> NetMessage for ${typeName}<'a> {
    const STRIDE: usize = ${layout.stride};

    fn measure(&self, cursor: usize) -> usize {
        let mut cursor = cursor;
${measures.map(line => indent(line, 8)).join('\n')}
        cursor
    }

    fn write_message(&self, buf: &mut [u8], at: usize, heap: usize, cursor: &mut usize) {
        let _ = (heap, &cursor);
${writes.map(line => indent(line, 8)).join('\n')}
    }
}${kinds}

/// Reader side of \`${typeName}\`: reads a validated packet in place.
#[derive(Clone, Copy)]
pub struct ${typeName}View<'a> {
    record: &'a [u8],
    heap: &'a [u8],
}

impl<'a> ${typeName}View<'a> {
${accessors.map(line => indent(line, 4)).join('\n\n')}
}

impl<'a> NetView<'a> for ${typeName}View<'a> {
    const STRIDE: usize = ${layout.stride};

    fn from_parts(record: &'a [u8], heap: &'a [u8]) -> Self {
        Self { record, heap }
    }

    fn validate(record: &[u8], heap: &[u8], budget: &mut usize) -> Result<(), NetDecodeError> {
        let _ = (record, heap, &budget);
${validates.map(line => indent(line, 8)).join('\n')}
        Ok(())
    }
}

impl<'a> NetElement<'a> for ${typeName}View<'a> {
    const SIZE: usize = ${layout.stride};

    fn read_element(bytes: &'a [u8], heap: &'a [u8]) -> Self {
        Self::from_parts(bytes, heap)
    }
}`;
}

function emitHeapRuntime(): string {
  const scalars: AoSScalarType[] = [
    'bool',
    'i8',
    'u8',
    'i16',
    'u16',
    'i32',
    'u32',
    'f32',
    'i64',
    'u64',
    'f64',
  ];
  const scalarElements = scalars
    .map(
      type => `impl<'a> NetElement<'a> for ${type} {
    const SIZE: usize = ${scalarByteSize(type)};

    fn read_element(bytes: &'a [u8], _heap: &'a [u8]) -> Self {
        get_${type}(bytes, 0)
    }
}`
    )
    .join('\n\n');

  return `// Variable-length data lives in a heap after the records, starting on an
// 8-byte boundary. A record holds a \`u32 offset | u32 count\` slot per field,
// with the offset relative to the heap and aligned for the element type.

/// Heap references a decode may follow, as a multiple of the packet's size.
/// Bounds the work a hostile packet can cause by pointing many slots at the
/// same data, the way Cap'n Proto's traversal limit does.
pub const NET_TRAVERSAL_FACTOR: usize = 8;

/// A record whose variable-length fields are written into the packet heap.
pub trait NetMessage {
    const STRIDE: usize;
    /// The heap cursor after this record's data, starting from \`cursor\`.
    fn measure(&self, cursor: usize) -> usize;
    /// Write the record at \`at\` in \`buf\`, reserving heap space from \`cursor\`
    /// (relative to the heap, which starts at \`heap\` in \`buf\`).
    fn write_message(&self, buf: &mut [u8], at: usize, heap: usize, cursor: &mut usize);
}

/// A message record with its own packet identity.
pub trait NetMessagePacket: NetMessage + Sized {
    const SCHEMA_ID: u32;
    const VERSION: u16;
    const SCHEMA_HASH: u64;

    fn encode(&self) -> Vec<u8> {
        let mut out = Vec::new();
        self.encode_into(&mut out);
        out
    }

    /// Encode into \`out\`, replacing its contents and reusing its capacity.
    fn encode_into(&self, out: &mut Vec<u8>) {
        encode_net_messages_into(core::slice::from_ref(self), out)
    }
}

pub fn encode_net_messages_into<T: NetMessagePacket>(records: &[T], out: &mut Vec<u8>) {
    let mut heap_bytes = 0;
    for record in records {
        heap_bytes = record.measure(heap_bytes);
    }
    let heap = net_heap_start(T::STRIDE, records.len());
    net_packet_into(
        out,
        T::SCHEMA_ID,
        T::VERSION,
        T::SCHEMA_HASH,
        T::STRIDE,
        records.len(),
        heap - NET_HEADER_BYTES + heap_bytes,
    );
    let mut cursor = 0;
    for (i, record) in records.iter().enumerate() {
        record.write_message(out, NET_HEADER_BYTES + i * T::STRIDE, heap, &mut cursor);
    }
    debug_assert_eq!(cursor, heap_bytes);
}

/// A zero-copy reader over one record of a validated packet.
pub trait NetView<'a>: Sized + Copy {
    const STRIDE: usize;
    fn from_parts(record: &'a [u8], heap: &'a [u8]) -> Self;
    /// Check every heap reference reachable from \`record\`, charging \`budget\`.
    fn validate(record: &[u8], heap: &[u8], budget: &mut usize) -> Result<(), NetDecodeError>;
}

pub trait NetMessageView<'a>: NetView<'a> + NetElement<'a> + 'a {
    const SCHEMA_ID: u32;
    const VERSION: u16;
    const SCHEMA_HASH: u64;

    /// Every record in a packet. The whole packet is validated up front, so the
    /// accessors after it never fail.
    fn decode_batch(bytes: &'a [u8]) -> Result<NetList<'a, Self>, NetDecodeError> {
        let count = read_net_message_header(bytes, Self::SCHEMA_ID, Self::VERSION, Self::SCHEMA_HASH, Self::STRIDE)?;
        let records = &bytes[NET_HEADER_BYTES..NET_HEADER_BYTES + Self::STRIDE * count];
        let heap = &bytes[net_heap_start(Self::STRIDE, count)..];
        let mut budget = bytes.len().saturating_mul(NET_TRAVERSAL_FACTOR);
        for i in 0..count {
            Self::validate(&records[i * Self::STRIDE..(i + 1) * Self::STRIDE], heap, &mut budget)?;
        }
        Ok(NetList { bytes: records, heap, len: count, marker: core::marker::PhantomData })
    }

    /// The first record of a packet, like the TypeScript \`view*\` helpers.
    fn decode(bytes: &'a [u8]) -> Result<Self, NetDecodeError> {
        Self::decode_batch(bytes)?.get(0).ok_or(NetDecodeError::Empty)
    }
}

/// Something a \`NetList\` can hold: a scalar, a fixed record, or a view.
pub trait NetElement<'a>: Sized {
    const SIZE: usize;
    fn read_element(bytes: &'a [u8], heap: &'a [u8]) -> Self;
}

${scalarElements}

/// A list in the packet heap, read in place.
pub struct NetList<'a, T> {
    bytes: &'a [u8],
    heap: &'a [u8],
    len: usize,
    marker: core::marker::PhantomData<fn() -> T>,
}

impl<'a, T> Clone for NetList<'a, T> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<'a, T> Copy for NetList<'a, T> {}

impl<'a, T: NetElement<'a> + 'a> NetList<'a, T> {
    pub fn len(&self) -> usize {
        self.len
    }

    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    pub fn get(&self, index: usize) -> Option<T> {
        if index >= self.len {
            return None;
        }
        let at = index * T::SIZE;
        Some(T::read_element(&self.bytes[at..at + T::SIZE], self.heap))
    }

    pub fn iter(&self) -> impl Iterator<Item = T> + 'a {
        let list = *self;
        (0..list.len).filter_map(move |index| list.get(index))
    }
}

impl<'a, T: NetElement<'a> + core::fmt::Debug + 'a> core::fmt::Debug for NetList<'a, T> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_list().entries(self.iter()).finish()
    }
}

fn net_heap_start(stride: usize, count: usize) -> usize {
    NET_HEADER_BYTES + align_up(stride * count, 8)
}

fn read_net_message_header(
    bytes: &[u8],
    schema_id: u32,
    version: u16,
    schema_hash: u64,
    stride: usize,
) -> Result<usize, NetDecodeError> {
    if bytes.len() < NET_HEADER_BYTES {
        return Err(NetDecodeError::Truncated);
    }
    if get_u32(bytes, 0) != NET_MAGIC
        || get_u16(bytes, 4) != NET_CODEC_VERSION
        || get_u32(bytes, 8) != schema_id
        || get_u16(bytes, 12) != version
        || get_u16(bytes, 14) as usize != NET_HEADER_BYTES
        || get_u64(bytes, 16) != schema_hash
        || get_u32(bytes, 24) as usize != stride
    {
        return Err(NetDecodeError::SchemaMismatch);
    }
    let count = get_u32(bytes, 28) as usize;
    match stride.checked_mul(count).and_then(|n| n.checked_add(NET_HEADER_BYTES + 7)) {
        Some(end) if end / 8 * 8 <= bytes.len() => Ok(count),
        _ => Err(NetDecodeError::InvalidLength),
    }
}

#[inline]
fn net_slot(record: &[u8], slot: usize) -> (usize, usize) {
    (get_u32(record, slot) as usize, get_u32(record, slot + 4) as usize)
}

fn net_validate_slot(
    record: &[u8],
    slot: usize,
    heap: &[u8],
    size: usize,
    budget: &mut usize,
) -> Result<(usize, usize), NetDecodeError> {
    let (start, len) = net_slot(record, slot);
    let bytes = len.checked_mul(size).ok_or(NetDecodeError::HeapOutOfBounds)?;
    match start.checked_add(bytes) {
        Some(end) if end <= heap.len() => {}
        _ => return Err(NetDecodeError::HeapOutOfBounds),
    }
    *budget = budget.checked_sub(bytes.max(len)).ok_or(NetDecodeError::TraversalLimit)?;
    Ok((start, len))
}

#[inline]
fn net_heap_bytes<'a>(record: &[u8], slot: usize, heap: &'a [u8]) -> &'a [u8] {
    let (start, len) = net_slot(record, slot);
    start.checked_add(len).and_then(|end| heap.get(start..end)).unwrap_or(&[])
}

#[inline]
fn net_heap_str<'a>(record: &[u8], slot: usize, heap: &'a [u8]) -> &'a str {
    core::str::from_utf8(net_heap_bytes(record, slot, heap)).unwrap_or("")
}

#[inline]
fn net_list<'a, T: NetElement<'a>>(record: &[u8], slot: usize, heap: &'a [u8]) -> NetList<'a, T> {
    let (start, len) = net_slot(record, slot);
    let bytes = len
        .checked_mul(T::SIZE)
        .and_then(|n| start.checked_add(n))
        .and_then(|end| heap.get(start..end));
    match bytes {
        Some(bytes) => NetList { bytes, heap, len, marker: core::marker::PhantomData },
        None => NetList { bytes: &[], heap, len: 0, marker: core::marker::PhantomData },
    }
}

#[inline]
fn net_measure(cursor: usize, len: usize, size: usize, alignment: usize) -> usize {
    align_up(cursor, alignment) + len * size
}

fn net_reserve(
    buf: &mut [u8],
    slot: usize,
    heap: usize,
    cursor: &mut usize,
    len: usize,
    size: usize,
    alignment: usize,
) -> usize {
    let start = align_up(*cursor, alignment);
    *cursor = start + len * size;
    put_u32(buf, slot, u32::try_from(start).expect("net heap exceeds u32"));
    put_u32(buf, slot + 4, u32::try_from(len).expect("net list length exceeds u32"));
    heap + start
}`;
}

function rustScalar(type: AoSScalarType): string {
  return type;
}

function scalarDefault(type: AoSScalarType): string {
  if (type === 'bool') return 'false';
  if (type === 'f32' || type === 'f64') return '0.0';
  return '0';
}

function scalarByteSize(type: AoSScalarType): number {
  if (type === 'bool' || type === 'i8' || type === 'u8') return 1;
  if (type === 'i16' || type === 'u16') return 2;
  if (type === 'i32' || type === 'u32' || type === 'f32') return 4;
  return 8;
}

const RUST_KEYWORDS = new Set([
  'as',
  'async',
  'await',
  'break',
  'const',
  'continue',
  'crate',
  'dyn',
  'else',
  'enum',
  'extern',
  'false',
  'fn',
  'for',
  'if',
  'impl',
  'in',
  'let',
  'loop',
  'match',
  'mod',
  'move',
  'mut',
  'pub',
  'ref',
  'return',
  'static',
  'struct',
  'trait',
  'true',
  'type',
  'unsafe',
  'use',
  'where',
  'while',
  'abstract',
  'become',
  'box',
  'do',
  'final',
  'gen',
  'macro',
  'override',
  'priv',
  'try',
  'typeof',
  'unsized',
  'virtual',
  'yield',
]);

function rustIdent(name: string): string {
  const snake = snakeCase(name);
  return RUST_KEYWORDS.has(snake) ? `r#${snake}` : snake;
}

function snakeCase(name: string): string {
  return name
    .replace(/\$/g, '_')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

function constantName(name: string): string {
  return snakeCase(name).toUpperCase();
}

function capitalize(value: string): string {
  return value.length ? value[0]!.toUpperCase() + value.slice(1) : value;
}

function indent(value: string, spaces: number): string {
  const prefix = ' '.repeat(spaces);
  return value
    .split('\n')
    .map(line => (line ? `${prefix}${line}` : line))
    .join('\n');
}
