/* eslint-disable */
// GENERATED by client/scripts/material-ai/generate-terrain-palette-registry.mjs
// Do not edit. Change a family recipe and rebuild instead.

import type { EltaniaTerrainMaterial, EltaniaTerrainRole } from './terrain-palette';

export const ELTANIA_TERRAIN_PALETTE_FAMILIES = ["eltania-ground-v1"] as const;

export const ELTANIA_TERRAIN_ROLE_LABELS: Readonly<Record<EltaniaTerrainRole, string>> = {
  "terrain.grass": "Grass",
  "terrain.path": "Paths and wear",
  "terrain.soil": "Soil and litter",
  "terrain.gravel": "Gravel and scree",
  "terrain.rock": "Stone"
};

export const ELTANIA_TERRAIN_PALETTE_MATERIALS: readonly EltaniaTerrainMaterial[] = [
  {
    "id": "eltania-ground-v1/cliffRock",
    "family": "eltania-ground-v1",
    "key": "cliffRock",
    "label": "Exposed cliff stone",
    "role": "terrain.rock",
    "note": "exposed natural cliff stone; the triplanar steep-slope layer",
    "source": "rock_face_03",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/cliffRock-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/cliffRock-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/cliffRock-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/cliffRock-preview.webp",
    "tileMetres": 8,
    "normalScale": 1.3,
    "roughness": 0.96,
    "heightContrast": 0.8
  },
  {
    "id": "eltania-ground-v1/earthDamp",
    "family": "eltania-ground-v1",
    "key": "earthDamp",
    "label": "Damp earth and mud",
    "role": "terrain.soil",
    "note": "damp hollows, ditches, and water-adjacent ground",
    "source": "brown_mud_leaves_01",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/earthDamp-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/earthDamp-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/earthDamp-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/earthDamp-preview.webp",
    "tileMetres": 4.5,
    "normalScale": 1.2,
    "roughness": 0.94,
    "heightContrast": 0.6
  },
  {
    "id": "eltania-ground-v1/earthPacked",
    "family": "eltania-ground-v1",
    "key": "earthPacked",
    "label": "Packed earth track",
    "role": "terrain.path",
    "note": "packed path and cart-track dirt",
    "source": "dirt_floor",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/earthPacked-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/earthPacked-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/earthPacked-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/earthPacked-preview.webp",
    "tileMetres": 4,
    "normalScale": 1.1,
    "roughness": 1,
    "heightContrast": 0.45
  },
  {
    "id": "eltania-ground-v1/forestLitter",
    "family": "eltania-ground-v1",
    "key": "forestLitter",
    "label": "Forest floor litter",
    "role": "terrain.soil",
    "note": "needle and leaf duff under closed canopy",
    "source": "forrest_ground_01",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/forestLitter-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/forestLitter-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/forestLitter-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/forestLitter-preview.webp",
    "tileMetres": 4.5,
    "normalScale": 1.3,
    "roughness": 1,
    "heightContrast": 0.7
  },
  {
    "id": "eltania-ground-v1/grassDry",
    "family": "eltania-ground-v1",
    "key": "grassDry",
    "label": "Dry highland grass",
    "role": "terrain.grass",
    "note": "dry highland and late-season grass; the lush scan dried, so the two blade layers blend without a change of surface",
    "source": "leafy_grass",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/grassDry-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/grassDry-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/grassDry-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/grassDry-preview.webp",
    "tileMetres": 6,
    "normalScale": 1.2,
    "roughness": 1,
    "heightContrast": 0.55
  },
  {
    "id": "eltania-ground-v1/grassLush",
    "family": "eltania-ground-v1",
    "key": "grassLush",
    "label": "Lush meadow grass",
    "role": "terrain.grass",
    "note": "dense meadow turf, the default flat-ground surface",
    "source": "leafy_grass",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/grassLush-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/grassLush-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/grassLush-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/grassLush-preview.webp",
    "tileMetres": 6,
    "normalScale": 1.2,
    "roughness": 1,
    "heightContrast": 0.55
  },
  {
    "id": "eltania-ground-v1/grassSparse",
    "family": "eltania-ground-v1",
    "key": "grassSparse",
    "label": "Sparse grass over soil",
    "role": "terrain.grass",
    "note": "thin grass over showing soil; the natural grass-to-dirt transition",
    "source": "sparse_grass",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/grassSparse-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/grassSparse-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/grassSparse-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/grassSparse-preview.webp",
    "tileMetres": 5.5,
    "normalScale": 1.25,
    "roughness": 1,
    "heightContrast": 0.6
  },
  {
    "id": "eltania-ground-v1/grassWorn",
    "family": "eltania-ground-v1",
    "key": "grassWorn",
    "label": "Worn grass verge",
    "role": "terrain.path",
    "note": "trodden grass verge either side of a track",
    "source": "grass_path_2",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/grassWorn-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/grassWorn-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/grassWorn-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/grassWorn-preview.webp",
    "tileMetres": 5,
    "normalScale": 1.15,
    "roughness": 1,
    "heightContrast": 0.5
  },
  {
    "id": "eltania-ground-v1/gravel",
    "family": "eltania-ground-v1",
    "key": "gravel",
    "label": "River gravel",
    "role": "terrain.gravel",
    "note": "road base, ford, and yard gravel",
    "source": "ganges_river_pebbles",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/gravel-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/gravel-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/gravel-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/gravel-preview.webp",
    "tileMetres": 3,
    "normalScale": 1.35,
    "roughness": 1,
    "heightContrast": 0.85
  },
  {
    "id": "eltania-ground-v1/rockMossy",
    "family": "eltania-ground-v1",
    "key": "rockMossy",
    "label": "Mossed wet stone",
    "role": "terrain.rock",
    "note": "damp mossed outcrop for shaded and wet stone",
    "source": "mossy_rock",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/rockMossy-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/rockMossy-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/rockMossy-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/rockMossy-preview.webp",
    "tileMetres": 7,
    "normalScale": 1.3,
    "roughness": 0.98,
    "heightContrast": 0.75
  },
  {
    "id": "eltania-ground-v1/scree",
    "family": "eltania-ground-v1",
    "key": "scree",
    "label": "Loose scree",
    "role": "terrain.gravel",
    "note": "loose scree collecting at a cliff base",
    "source": "dry_ground_rocks",
    "textures": {
      "albedo": "/eltania/terrain/palette/eltania-ground-v1/scree-albedo.webp",
      "normal": "/eltania/terrain/palette/eltania-ground-v1/scree-normal.webp",
      "hrm": "/eltania/terrain/palette/eltania-ground-v1/scree-hrm.webp"
    },
    "preview": "/eltania/terrain/palette/eltania-ground-v1/previews/scree-preview.webp",
    "tileMetres": 3.5,
    "normalScale": 1.4,
    "roughness": 1,
    "heightContrast": 0.9
  }
];
