// Generated by shado asc build. Do not edit.

@unmanaged
class ShadoEntity2DHeader {
  positionSize_x:f32; positionSize_y:f32; positionSize_z:f32; positionSize_w:f32;
  render_x:f32; render_y:f32; render_z:f32; render_w:f32;
  destinationSize_x:f32; destinationSize_y:f32; destinationSize_z:f32; destinationSize_w:f32;
  motion_x:f32; motion_y:f32; motion_z:f32; motion_w:f32;
  uvRect_x:f32; uvRect_y:f32; uvRect_z:f32; uvRect_w:f32;
  color_x:f32; color_y:f32; color_z:f32; color_w:f32;
  renderState_x:f32; renderState_y:f32; renderState_z:f32; renderState_w:f32;
}
export const OFFSET_ShadoEntity2D_positionSize: i32 = 0;
export const OFFSET_ShadoEntity2D_render: i32 = 16;
export const OFFSET_ShadoEntity2D_destinationSize: i32 = 32;
export const OFFSET_ShadoEntity2D_motion: i32 = 48;
export const OFFSET_ShadoEntity2D_uvRect: i32 = 64;
export const OFFSET_ShadoEntity2D_color: i32 = 80;
export const OFFSET_ShadoEntity2D_renderState: i32 = 96;
export const SIZEOF_ShadoEntity2DHeader: i32 = 112;


@unmanaged
export class ShadoDynamicEntityDeltaRecord {
  op: u32;
  index: i32;
  positionSize_x: f32; positionSize_y: f32; positionSize_z: f32; positionSize_w: f32;
  z: f32;
  speed: f32;
  flags: u32;
  removeAfterFrame: i32;
  removeAfterSimulationTime: f64;
}
export const OFFSET_ShadoDynamicEntityDeltaRecord_op: i32 = 0;
export const OFFSET_ShadoDynamicEntityDeltaRecord_index: i32 = 4;
export const OFFSET_ShadoDynamicEntityDeltaRecord_positionSize: i32 = 8;
export const OFFSET_ShadoDynamicEntityDeltaRecord_z: i32 = 24;
export const OFFSET_ShadoDynamicEntityDeltaRecord_speed: i32 = 28;
export const OFFSET_ShadoDynamicEntityDeltaRecord_flags: i32 = 32;
export const OFFSET_ShadoDynamicEntityDeltaRecord_removeAfterFrame: i32 = 36;
export const OFFSET_ShadoDynamicEntityDeltaRecord_removeAfterSimulationTime: i32 = 40;
export const SIZEOF_ShadoDynamicEntityDeltaRecord: i32 = 48;

@unmanaged
export class ShadoDynamicEntityExpirationRecord {
  index: i32;
  removeAfterFrame: i32;
  flags: i32;
  padding: i32;
  removeAfterSimulationTime: f64;
}
export const OFFSET_ShadoDynamicEntityExpirationRecord_index: i32 = 0;
export const OFFSET_ShadoDynamicEntityExpirationRecord_removeAfterFrame: i32 = 4;
export const OFFSET_ShadoDynamicEntityExpirationRecord_flags: i32 = 8;
export const OFFSET_ShadoDynamicEntityExpirationRecord_padding: i32 = 12;
export const OFFSET_ShadoDynamicEntityExpirationRecord_removeAfterSimulationTime: i32 = 16;
export const SIZEOF_ShadoDynamicEntityExpirationRecord: i32 = 24;
